### ISSUE TITLE
CVI cannot open iPhone created KTX files

### ISSUE THREAD

**Issue by bensh** [castle-engine/castle-view-image#1]
iOS creates a 'snapshot' of an app when it is sent to the background. This image is used when the app resumes to make it look like it is resuming quicker.
These image files are stored in Library/Caches/Snapshots of jailbroken devices.

Opening one of these images in CVI meets the following error.
![image](https://user-images.githubusercontent.com/3234569/112983014-0fe75a80-9155-11eb-9a7b-17a5c2f12cb8.png)

[ktx_test_file.zip](https://github.com/castle-engine/castle-view-image/files/6228699/ktx_test_file.zip)

**Comment by michaliskambi** [comment]
Thanks for the report! This is a KTX with GPU compression = ASTC_4x4_KHR (`0x93B0`).

1. The initial bug was that `castle-view-image` (actually [Castle Game Engine](https://castle-engine.io/) used underneath) reported error, because it didn't expect glTypeSize = 0 for compressed textures. But it seems KTX spec allows it, so we do too now.

2. Unfortunately this only leads me to another error, and I don't know yet what to do with it (all signs indicate that KTX is just very wrong).

    Namely, the file is way too small. It contains an image with size 750 x 1334 in pixels, and the data size in bytes should be 172 + 1004672 using ASTC_4x4_KHR compression formula (16 bytes for each 4x4 block). But the actual data size is 6503 (a weird odd number for ASTC, not divisible even by 2), both looking at image header information (imageSize field) and actual file size.

    - Are you sure this is the complete file?

    - Do you know of any application, aside from iOS system, that can open such files?

3. Warning: Even if we fix AD 2, displaying this file with `castle-view-image` will not work on all systems. In case of GPU compression like `ASTC_4x4_KHR`, `castle-view-image` just asks GPU to handle `ASTC_4x4_KHR` compression, which is not guaranteed, it just depends on your graphic card and installed drivers. It is handled now on my current GPU on Linux (in the log I see `Compressed textures supported: [..., ASTC_4x4_RGBA, ...]`). If your GPU doesn't support it, unfortunately all you will see is a message like

    `Cannot decompress texture: Cannot load textures compressed usingASTC_4x4_RGBA, your OpenGL/OpenGLES does not support the necessary extensions`

**Comment by bensh** [comment]
Hi!
- As far as I know it was the complete image, I have provided another 2 anyway for your testing
- MacOS works and can read these without issue or separate software. It classes these as 'KTX textures' and can open them with either Finder 'press Spacebar' or Preview 'system default file handler'
- I found the file on  a laptop using Intel HD onboard graphics; after a quick Google, it seems some of these chipsets do support OpenGL, some don't...... at least the bug could be fixed anyway.

[Archive.zip](https://github.com/castle-engine/castle-view-image/files/6262585/Archive.zip)

**Comment by michaliskambi** [comment]
Sorry for the delay! COVID got me, and just now I'm finally getting better.

Investigating your 2 new images: hm, they are still too small. The image data seems ~5x smaller than what we need for ASTC_4x4_RGBA encoding.

```
ktx1.ktx:
Compression tcASTC_4x4_RGBA
Expected bytes: 1004672
Expected bytes (counted again): (w + 3) / 4 * (h + 3) / 4 * 16 = (750 + 3) / 4 * (1334 + 3) / 4 * 16 = 1004672
Got bytes: 202894

ktx2.ktx:
Compression tcASTC_4x4_RGBA
Expected bytes: 1004672
Expected bytes (counted again): (w + 3) / 4 * (h + 3) / 4 * 16 = (1334 + 3) / 4 * (750 + 3) / 4 * 16 = 1004672
Got bytes: 195104
```

I resorted to searching the Internet:

- https://www.swiftforensics.com/2020/07/ktx-to-png-in-python-for-ios-snapshots.html explains it:

    Apple applies additional LZFSE compression over the data ( https://developer.apple.com/documentation/compression/algorithm/lzfse , https://en.wikipedia.org/wiki/LZFSE ).

- A Python script that does a proper job of decoding (with extra step to decode LZFSE) is on https://github.com/ydkhatri/MacForensics/blob/master/IOS_KTX_TO_PNG/ios_ktx2png.py .

    Just tested it, works nicely. Installation and usage:

    ```
    pip3 install pyliblzfse astc_decomp pillow
    # get ios_ktx2png.py from https://github.com/ydkhatri/MacForensics/blob/master/IOS_KTX_TO_PNG/ios_ktx2png.py
    python3 ./ios_ktx2png.py D06B2F0D-BF50-4391-8785-AC086DC0C894\@2x.ktx
    python3 ./ios_ktx2png.py ktx2.ktx
    ```

All right! So the mystery is solved, and there's a working software that reads these KTX files.

Unfortunately it means that it's not really something I see implemented in Castle Game Engine / castle-view-image. We do not have a ready LZFSE decompression library in FPC. I could integrate with an external library, but this seems too much burden for reading such special KTX files (from what I know, the KTX specification doesn't say to use LZFSE anywhere, and so far I didn't encounter other cases of such KTX files; looks like adding LZFSE compression is a non-standard Apple invention).

Sorry -- but the burden of implementing LZFSE decompression in CGE for this seems too much, at least for now for me.

I would recommend trying the above Python script. In effect you get a normal PNG file that can be further opened by anything :)

Attaching some conversion results.
![D06B2F0D-BF50-4391-8785-AC086DC0C894@2x ktx](https://user-images.githubusercontent.com/1076978/116325383-4cdd5600-a7c2-11eb-8327-0b5b093432e5.png)
![ktx1 ktx](https://user-images.githubusercontent.com/1076978/116325385-4d75ec80-a7c2-11eb-893a-818af9316088.png)
![ktx2 ktx](https://user-images.githubusercontent.com/1076978/116325387-4ea71980-a7c2-11eb-8f47-d731f90a9c76.png)
