### ISSUE TITLE
Compilation from sources instructions do not work

### ISSUE THREAD

**Issue by the-Arioch** [castle-engine/castle-view-image#2]
Trying step 8 on https://castle-engine.io/compiling_from_source.php i get an error: required package castle_window not found.

I found the package in sources, compiled it and then compiled the viewer. Just, the manual has to be updated

**Comment by michaliskambi** [comment]
Thanks, I updated https://castle-engine.io/compiling_from_source.php to clearly say this -- for both view3dscene and castle-view-image.

> First, Lazarus must be aware of the castle_window package. It is best to use Register Lazarus Packages button from the CGE editor, as described in the Installation manual. Or you could just open the packages/castle_window.lpk package in CGE sources, and "Compile" it from Lazarus.
